//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Domain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Domain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Domain", typeof(Domain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string ArticleBody {
            get {
                return ResourceManager.GetString("ArticleBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headline.
        /// </summary>
        public static string ArticleHeadline {
            get {
                return ResourceManager.GetString("ArticleHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact type name too long..
        /// </summary>
        public static string ContactTypeNameLengthError {
            get {
                return ResourceManager.GetString("ContactTypeNameLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact too long..
        /// </summary>
        public static string ContactValueLengthError {
            get {
                return ResourceManager.GetString("ContactValueLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End bet.
        /// </summary>
        public static string EndBet {
            get {
                return ResourceManager.GetString("EndBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string EntityPrimaryKey {
            get {
                return ResourceManager.GetString("EntityPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First, Lastname.
        /// </summary>
        public static string FirstLastname {
            get {
                return ResourceManager.GetString("FirstLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name too long..
        /// </summary>
        public static string FirstnameLengthError {
            get {
                return ResourceManager.GetString("FirstnameLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game name.
        /// </summary>
        public static string GameName {
            get {
                return ResourceManager.GetString("GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamerow description.
        /// </summary>
        public static string GameRowDescription {
            get {
                return ResourceManager.GetString("GameRowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamerow description.
        /// </summary>
        public static string GameRowTypeDescription {
            get {
                return ResourceManager.GetString("GameRowTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game type name.
        /// </summary>
        public static string GameTypeName {
            get {
                return ResourceManager.GetString("GameTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last, Firstname.
        /// </summary>
        public static string LastFirstname {
            get {
                return ResourceManager.GetString("LastFirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name too long..
        /// </summary>
        public static string LastnameLengthError {
            get {
                return ResourceManager.GetString("LastnameLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Person_Date2 {
            get {
                return ResourceManager.GetString("Person_Date2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and Time.
        /// </summary>
        public static string Person_DateTime2 {
            get {
                return ResourceManager.GetString("Person_DateTime2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Person_Time2 {
            get {
                return ResourceManager.GetString("Person_Time2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment about person&apos;s gamerow.
        /// </summary>
        public static string PersonGameRowComment {
            get {
                return ResourceManager.GetString("PersonGameRowComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person name.
        /// </summary>
        public static string PersonName {
            get {
                return ResourceManager.GetString("PersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register date.
        /// </summary>
        public static string RegisterDate {
            get {
                return ResourceManager.GetString("RegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort order.
        /// </summary>
        public static string SortOrder {
            get {
                return ResourceManager.GetString("SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start bet.
        /// </summary>
        public static string StartBet {
            get {
                return ResourceManager.GetString("StartBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started at.
        /// </summary>
        public static string StartedAt {
            get {
                return ResourceManager.GetString("StartedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped at.
        /// </summary>
        public static string StoppedAt {
            get {
                return ResourceManager.GetString("StoppedAt", resourceCulture);
            }
        }
    }
}
